name: Shantu PDF Test


on:

  # 手动运行
  workflow_dispatch:


  # 每天北京时间9点
  schedule:
    - cron: "0 1 * * *"



jobs:

  build:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout
        uses: actions/checkout@v4



      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"



      - name: Install requirements
        run: |
          pip install -r shantu/requirements.txt



      - name: Run PDF parser
        run: |
          python shantu/scripts/build_index.py



      - name: Upload result
        if: hashFiles('shantu/result/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: shantu-result
          path: shantu/result
